name: kraftdata
version: "1.0.0"
profile: kraftdata

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: target
clean-targets: [target, dbt_packages]

models:
  kraftdata:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  kraftdata:
    +schema: staging
